# Generated by Django 5.0.2 on 2024-02-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=3, max_digits=50)),
                ("available_stock", models.IntegerField()),
                ("images_url", models.CharField(max_length=500)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
