# Generated by Django 5.0.2 on 2024-02-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
