# Generated by Django 5.0.2 on 2024-02-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_products", "0002_alter_product_images_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available_stock",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
