# Generated by Django 5.0.2 on 2024-02-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_cart", "0004_remove_cartproduct_cart_remove_cartproduct_product_and_more"),
        ("a_products", "0003_alter_product_available_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="a_cart.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="a_products.product",
            ),
        ),
    ]
